// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PraOndeFoi.Data;

#nullable disable

namespace PraOndeFoi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PraOndeFoi.Models.AnexoTransacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConteudoTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TransacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.ToTable("AnexosTransacao");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Assinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervaloQuantidade")
                        .HasColumnType("integer");

                    b.Property<int>("IntervaloUnidade")
                        .HasColumnType("integer");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProximaCobranca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId", "Ativa", "ProximaCobranca");

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Predefinida")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salário",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Freelance",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aluguel",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Alimentação",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Transporte",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Saúde",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Educação",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Lazer",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Investimentos",
                            Predefinida = true
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Assinaturas",
                            Predefinida = true
                        });
                });

            modelBuilder.Entity("PraOndeFoi.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("PraOndeFoi.Models.MetaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId", "DataInicio");

                    b.ToTable("MetasFinanceiras");
                });

            modelBuilder.Entity("PraOndeFoi.Models.OrcamentoMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Limite")
                        .HasColumnType("numeric");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId", "Mes", "Ano", "CategoriaId")
                        .IsUnique();

                    b.ToTable("OrcamentosMensais");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Recorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DiaDoMes")
                        .HasColumnType("integer");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervaloQuantidade")
                        .HasColumnType("integer");

                    b.Property<int>("IntervaloUnidade")
                        .HasColumnType("integer");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProximaExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId", "Ativa", "ProximaExecucao");

                    b.ToTable("Recorrencias");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Nome")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId", "DataTransacao");

                    b.HasIndex("ContaId", "CategoriaId", "DataTransacao");

                    b.HasIndex("ContaId", "Tipo", "DataTransacao");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("PraOndeFoi.Models.TransacaoTag", b =>
                {
                    b.Property<int>("TransacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("TransacaoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransacaoTags");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PraOndeFoi.Models.AnexoTransacao", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Transacao", "Transacao")
                        .WithMany("Anexos")
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Assinatura", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Conta", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Usuario", "Usuario")
                        .WithOne("Conta")
                        .HasForeignKey("PraOndeFoi.Models.Conta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PraOndeFoi.Models.MetaFinanceira", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.OrcamentoMensal", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Recorrencia", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Tag", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Transacao", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraOndeFoi.Models.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("PraOndeFoi.Models.TransacaoTag", b =>
                {
                    b.HasOne("PraOndeFoi.Models.Tag", "Tag")
                        .WithMany("Transacoes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraOndeFoi.Models.Transacao", "Transacao")
                        .WithMany("Tags")
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Tag", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Transacao", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PraOndeFoi.Models.Usuario", b =>
                {
                    b.Navigation("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
